// import "./js/mobile-menu.js"
import "./js/modal.js"
import "./js/swiper-init.js"
 import "./js/swiper.js"
// import "./js/swiper-bandle.js"
// import "https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"
